"""Builds the Red Dead spawn menu's model list: gmod/addon/lua/gr/models_data.lua.

    python tools/gen_models.py            download the lists and write the file
    python tools/gen_models.py --if-missing   only if the file is not there yet

The names come from the community's lists in github.com/femga/rdr3_discoveries (peds,
vehicles, objects), which carry no licence. So the generated file is not committed: it
is made on the machine that builds the addon, and holds model names only, never anything
of the game's. The spawn menu also takes any model name typed into its search box.
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "gmod", "addon", "lua", "gr", "models_data.lua")
BASE = "https://raw.githubusercontent.com/femga/rdr3_discoveries/master/"

# Folders of the object list whose p_ models are things to spawn rather than pieces of the
# map (lev_des, structure, areas) or plants.
OBJECT_FOLDERS = {"generic", "interior", "urban", "vehicle_props"}

HORSE = re.compile(r"^a_c_(horse|donkey)")


def fetch(path):
    with urllib.request.urlopen(BASE + path, timeout=60) as r:
        return r.read().decode("utf-8", errors="replace")


def build():
    peds = re.findall(r'\{\s*0x[0-9A-Fa-f]+\s*,\s*"([^"]+)"', fetch("peds/peds_list.lua"))
    vehicles = re.findall(r'\[0x[0-9A-Fa-f]+\]\s*=\s*"([^"]+)"', fetch("vehicles/vehicles_list.lua"))
    objects = []
    for name, folder in re.findall(r'=\s*"([^"]+)"\s*,\s*--\s*hex_hash:\s*\S+\s*--\s*([^|\n]+)\|',
                                   fetch("objects/object_list.lua")):
        if name.lower().startswith("p_") and folder.strip() in OBJECT_FOLDERS:
            objects.append(name)

    people, horses, animals = [], [], []
    for name in peds:
        n = name.lower()
        if HORSE.match(n):
            horses.append(n)
        elif n.startswith("a_c_"):
            animals.append(n)
        else:
            people.append(n)

    lists = {
        "people": people,
        "horses": horses,
        "animals": animals,
        "vehicles": [v.lower() for v in vehicles],
        "objects": [o.lower() for o in objects],
    }
    lines = [
        "-- Generated by tools/gen_models.py from github.com/femga/rdr3_discoveries. Do not edit,",
        "-- do not commit: run the script again.",
        "GR.ModelData = {",
    ]
    for key, names in lists.items():
        names = sorted(set(names))
        lines.append(f"    {key} = {{")
        for i in range(0, len(names), 8):
            lines.append("        " + " ".join(f'"{n}",' for n in names[i:i + 8]))
        lines.append("    },")
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{OUT}: " + ", ".join(f"{len(set(v))} {k}" for k, v in lists.items()))


if __name__ == "__main__":
    if "--if-missing" in sys.argv and os.path.exists(OUT):
        sys.exit(0)
    build()
